import Footer from '@components/Footer';
import Navigation from '@components/Navigation';
import NextAuthProvider from '@components/NextAuthProvider';
import ReactQueryProvider from '@components/ReactQueryProvider';
import StyledComponentsRegistry from '@lib/AntdRegistry';
import '@styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className='md:bg-gray-100'>
        <StyledComponentsRegistry>
          <NextAuthProvider>
            <Navigation />
            <main className='app'>
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </main>
          </NextAuthProvider>
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
