import ReactQueryProvider from '@components/ReactQueryProvider';
import '@styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <main className='py-8 sm:px-72 md:px-16 px-8'>
      <ReactQueryProvider>{children}</ReactQueryProvider>
    </main>
  );
}
